# Generated by Django 3.2 on 2022-01-15 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField()),
                ('free', models.BooleanField(default=True)),
                ('date', models.DateTimeField(verbose_name='reservation date and time')),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='time',
        ),
        migrations.AddField(
            model_name='guest',
            name='fullname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.AddField(
            model_name='table',
            name='reserve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.guest'),
        ),
    ]
