# Generated by Django 3.2 on 2022-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20220115_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='fullname',
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
