# Generated by Django 3.2 on 2022-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20220115_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='tablesizes',
            field=models.ManyToManyField(to='tables.Size'),
        ),
    ]
